//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rentacar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class car
    {
        public int carid { get; set; }
        public string name { get; set; }
        public string pic { get; set; }
        public string fueltype { get; set; }
        public Nullable<int> seater { get; set; }
        public Nullable<double> fare { get; set; }
        public string noplate { get; set; }
        public string status { get; set; }
    }
}
